package com.oshi.desktop.devsync

import com.oshi.messenger.network.v2.devsync.DevSyncVectorCheck
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * __DEVSYNC_DIRECT_2026_09_22__ The shared own-device-sync core, compiled from the Android tree,
 * against the golden vectors in docs/fixtures/devsync/ (generated by the independent Python
 * reference `devsync_ref.py`). Android runs the identical check in `DevSyncVectorsTest`.
 */
class DevSyncVectorsTest {
    @Test
    fun goldenVectors_allMatch() {
        val report = DevSyncVectorCheck.runAll()
        println("devsync vectors: " + report.toString().lineSequence().first())
        assertEquals(report.toString(), 0, report.failures)
        assertTrue("suspiciously few checks: ${report.passes}", report.passes > 150)
    }

    /** Tripwire: a single flipped byte in a vector must be caught (the check is not vacuous). */
    @Test
    fun corruptedVector_isDetected() {
        val src = DevSyncVectorCheck.locate()
        val tmp = kotlin.io.path.createTempDirectory("devsync-vectors").toFile()
        try {
            src.listFiles()!!.filter { it.name.endsWith(".json") }.forEach { it.copyTo(java.io.File(tmp, it.name)) }
            val f = java.io.File(tmp, "noise_handshake.json")
            val o = org.json.JSONObject(f.readText())
            val m2 = o.getJSONArray("cases").getJSONObject(0).getJSONObject("msg2")
            val hex = m2.getString("message")
            val flipped = (if (hex[70] == '0') '1' else '0')
            m2.put("message", hex.substring(0, 70) + flipped + hex.substring(71))
            f.writeText(o.toString())
            val report = DevSyncVectorCheck.runAll(tmp)
            assertTrue("a corrupted msg2 must fail", report.failures >= 1)
        } finally {
            tmp.deleteRecursively()
        }
    }
}
