package com.oshi.desktop.i18n.tools

import com.oshi.desktop.i18n.Catalog
import com.oshi.desktop.i18n.StringsFile
import java.io.File

/**
 * Converts the iOS `.lproj` tree into the checked-in JSON catalogs the desktop ships.
 *
 * Run by hand or from Gradle (`./gradlew i18nExtract -PoshiIosRoot=…`) and re-run by
 * `CatalogFreshnessTest` to prove the checked-in files still match the source. It writes
 * into `src/main/resources/i18n/`, which is COMMITTED — see [Catalog]'s doc for why the
 * generated form is checked in rather than produced at build time.
 *
 * ### Two catalogs, not one
 *
 * Each `.lproj` holds `Localizable.strings` AND `InfoPlist.strings`, and they are
 * SEPARATE assets: 3820 keys against 16. This project has a memory of exactly the
 * confusion that invites — a `Localizable.xcstrings` at 100% while the permission prompts
 * were English in 34 languages, because `InfoPlist.xcstrings` is a different file that
 * nobody had looked at. So both are extracted, filed separately, and counted separately.
 *
 * **What `InfoPlist.strings` maps to on the desktop.** Its 16 keys are iOS permission
 * prompts (`NSCameraUsageDescription`, `NSBluetoothAlwaysUsageDescription`, …) plus
 * `CFBundleDisplayName`. Windows and Linux have no permission-prompt strings at all:
 * there is no OS dialog asking the user to grant the camera, so 15 of the 16 map to
 * NOTHING and are extracted only so that the desktop never has to go back to the iOS tree
 * to answer a question about them. The sixteenth, `CFBundleDisplayName`, maps to real
 * installer metadata — jpackage's `--name` / `--description`, which become the Start Menu
 * shortcut and the `.deb` package description. **jpackage takes exactly one `--name` per
 * invocation and has no localised-metadata mechanism at all**, so the installer is
 * single-language by construction; `InfoPlistMappingTest` records that as a measured
 * property of jpackage 17's command line rather than an assumption.
 */
object CatalogExtractor {

    const val LOCALIZABLE = "Localizable"
    const val INFO_PLIST = "InfoPlist"

    data class Extraction(
        val tag: String,
        val localizable: Map<String, String>,
        val infoPlist: Map<String, String>,
    )

    /** `<root>/xx.lproj` → tag `xx`, skipping anything inside a build artifact. */
    fun localeDirs(iosRoot: File): List<File> =
        (iosRoot.listFiles() ?: emptyArray())
            .filter { it.isDirectory && it.name.endsWith(".lproj") }
            // `Base.lproj` is Interface Builder's, not a language.
            .filterNot { it.name == "Base.lproj" }
            .sortedBy { it.name }

    fun tagOf(lprojDir: File): String = lprojDir.name.removeSuffix(".lproj")

    fun extractAll(iosRoot: File): List<Extraction> = localeDirs(iosRoot).map { dir ->
        Extraction(
            tag = tagOf(dir),
            localizable = readOrEmpty(File(dir, "$LOCALIZABLE.strings")),
            infoPlist = readOrEmpty(File(dir, "$INFO_PLIST.strings")),
        )
    }

    private fun readOrEmpty(f: File): Map<String, String> =
        if (f.isFile) StringsFile.read(f) else emptyMap()

    /**
     * The exact bytes each generated file should hold, keyed by path relative to the
     * resources root. Returned rather than written so the freshness test can compare
     * without touching the working tree.
     */
    fun render(iosRoot: File): Map<String, String> {
        val all = extractAll(iosRoot)
        require(all.isNotEmpty()) {
            "no .lproj directories under ${iosRoot.absolutePath} — refusing to generate an " +
                "empty catalog set, because that is indistinguishable from an app with no " +
                "translations and it would pass every 'the files parsed' check."
        }
        val out = LinkedHashMap<String, String>()
        for (e in all) {
            out["i18n/$LOCALIZABLE/${e.tag}.json"] = Catalog.write(e.localizable)
            out["i18n/$INFO_PLIST/${e.tag}.json"] = Catalog.write(e.infoPlist)
        }
        out["i18n/locales.txt"] = buildString {
            append("# Generated by CatalogExtractor from the iOS .lproj tree. Do not edit.\n")
            append("# One BCP-47 tag per line; each has a Localizable/<tag>.json and an\n")
            append("# InfoPlist/<tag>.json beside it.\n")
            all.forEach { append(it.tag).append('\n') }
        }
        return out
    }

    /** Write [render]'s output under [resourcesDir], deleting stale locale files. */
    fun writeTo(iosRoot: File, resourcesDir: File): List<File> {
        val rendered = render(iosRoot)
        val written = ArrayList<File>()
        for ((rel, body) in rendered) {
            val f = File(resourcesDir, rel)
            f.parentFile.mkdirs()
            f.writeText(body, Charsets.UTF_8)
            written.add(f)
        }
        // A locale REMOVED upstream must disappear here too, or the app keeps offering a
        // language the asset no longer has.
        val keep = rendered.keys.map { File(resourcesDir, it).canonicalPath }.toSet()
        for (sub in listOf(LOCALIZABLE, INFO_PLIST)) {
            File(resourcesDir, "i18n/$sub").listFiles()?.forEach {
                if (it.canonicalPath !in keep) it.delete()
            }
        }
        return written
    }

    @JvmStatic
    fun main(args: Array<String>) {
        require(args.size == 2) {
            "usage: CatalogExtractor <iosRoot> <resourcesDir>"
        }
        val written = writeTo(File(args[0]), File(args[1]))
        println("wrote ${written.size} file(s) under ${args[1]}")
    }
}
