package com.oshi.desktop.call

import com.oshi.messenger.network.v2.OSHICryptoV2
import java.util.Base64
import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * PARITY.md row 2.1 — the exact bytes of call signalling.
 *
 * ============================================================ HOW THESE ARE ANCHORED
 *
 * Every expectation below was derived by READING the shipped emitters, not by running
 * this package's encoder and pasting the result. That distinction is the whole reason
 * these tests are worth anything: a test whose expectation was generated by the code
 * under test proves self-consistency and nothing else, and this project has already paid
 * for exactly that shape once (a seed-recovery suite that "found 9/9 families" while
 * modelling the wrong Python version).
 *
 * The sources each golden value comes from:
 *
 *   iOS      `OSHI/VoiceCallManager.swift:13591-13602`  createCallPacket (the 9-byte header)
 *            `:1951-1975`                               CallPacketType raw values
 *            `:5936-5961`                               the offer body
 *            `:7338-7360`                               the accept body
 *            `:8219`, `:1872-1893`                      callEnd + CallEndReason spellings
 *            `:12833-12866`                             encryptForPeer (HKDF salt/info)
 *            `:3047-3052`                               responderNonceSalt (0xA5)
 *   Android  `EnhancedCallManager.kt:1385-1417`         the offer body, byte by byte
 *            `:1631-1643`                               the accept body (TWO cap bytes)
 *            `VPSClient.kt:1158-1173`                   the outer JSON envelope
 *            `CallOfferCapabilities.kt:12-56`           the peel and its invariant
 */
class CallWireFormatTest {

    /** A UUID of the shape both clients generate. Every byte is >= 0x2D. */
    private val callId = "1B2C3D4E-5F60-7182-9394-A5B6C7D8E9F0"

    /** Android's own wire tests use this base; reusing it keeps the two comparable. */
    private val baseMs = 1_770_000_000_000L

    private fun key32(fill: Byte) = ByteArray(32) { fill }
    private fun salt4() = byteArrayOf(0x11, 0x22, 0x33, 0x44)

    // ============================================================== the packet header

    /**
     * The header is `[type][timestampMs BE8]` — nine bytes, big-endian, Unix MILLIS.
     *
     * 1_770_000_000_000 = 0x0000_019C_1C38_A400, computed OUTSIDE this codebase (python
     * `hex(1770000000000)`) rather than by running the encoder — the point of a golden is
     * that it comes from somewhere else. The first draft of this test asserted
     * `0x...A6E4E000`, which was a hand-arithmetic slip; the test failed, the independent
     * computation settled it, and the expectation was corrected rather than the code.
     */
    @Test
    fun `packet header is type plus eight big-endian millisecond bytes`() {
        val p = CallPacket.encode(CallPacket.Type.CALL_DECLINE, baseMs)
        assertEquals("header is exactly 9 bytes with an empty body", 9, p.size)
        assertEquals(0x03, p[0].toInt() and 0xFF)
        assertEquals(
            "1770000000000 big-endian",
            listOf(0x00, 0x00, 0x01, 0x9C, 0x1C, 0x38, 0xA4, 0x00),
            (1..8).map { p[it].toInt() and 0xFF },
        )
    }

    /** Little-endian would put 0x00 first and 0x01 last — the classic silent inversion. */
    @Test
    fun `packet timestamp is not little-endian`() {
        val p = CallPacket.encode(CallPacket.Type.CALL_END, baseMs)
        assertFalse(
            "byte 1 must be the MOST significant byte",
            (p[1].toInt() and 0xFF) == 0x00 && (p[8].toInt() and 0xFF) == 0x01,
        )
    }

    /** The raw values, against iOS's enum at `VoiceCallManager.swift:1951-1975`. */
    @Test
    fun `packet type codes match the shipped enum`() {
        assertEquals(0x01, CallPacket.Type.CALL_REQUEST.code)
        assertEquals(0x02, CallPacket.Type.CALL_ACCEPT.code)
        assertEquals(0x03, CallPacket.Type.CALL_DECLINE.code)
        assertEquals(0x04, CallPacket.Type.CALL_END.code)
        assertEquals(0x08, CallPacket.Type.VIDEO_CALL_REQUEST.code)
        assertEquals(0x09, CallPacket.Type.VIDEO_CALL_ACCEPT.code)
        assertEquals(0x0A, CallPacket.Type.CALL_ANSWERED_ELSEWHERE.code)
        assertEquals(0x30, CallPacket.Type.ICE_CANDIDATE_EXCHANGE.code)
    }

    @Test
    fun `packet round-trips through decode`() {
        val body = byteArrayOf(1, 2, 3)
        val d = CallPacket.decode(CallPacket.encode(CallPacket.Type.CALL_END, baseMs, body))!!
        assertEquals(CallPacket.Type.CALL_END, d.type)
        assertEquals(baseMs, d.timestampMs)
        assertArrayEquals(body, d.payload)
        assertFalse(d.isLegacyForm)
    }

    /**
     * An unknown type byte is null, never a default.
     *
     * Android's `fromJson` DOES default a missing ENVELOPE type to CALL_REQUEST
     * (`VPSClient.kt:2470-2476`); copying that here would make every unrecognised packet
     * an incoming call on a server with no authentication.
     */
    @Test
    fun `an unknown type byte decodes to null rather than to a call request`() {
        val bogus = ByteArray(20).also { it[0] = 0x7F }
        assertNull(CallPacket.decode(bogus))
        assertNull(CallPacket.Type.fromCode(0x7F))
    }

    /** `VoiceCallManager.swift:13605-13617` — legacy tolerance is OFFER-ONLY. */
    @Test
    fun `the legacy headerless form is accepted for offers and refused for everything else`() {
        val offerBody = CallOffer(key32(7), salt4(), callId).encode()
        val legacyOffer = byteArrayOf(0x01) + offerBody
        val d = CallPacket.decode(legacyOffer)
        assertNotNull("a headerless offer is still an offer", d)
        assertTrue(d!!.isLegacyForm)
        assertNull("legacy form carries no instant", d.timestampMs)

        // A headerless callEnd would read "hung_up"'s first 8 bytes as a timestamp.
        val legacyEnd = byteArrayOf(0x04) + "hung_up".toByteArray()
        assertNull("a headerless terminal packet is a misparse, not a tolerance", CallPacket.decode(legacyEnd))
    }

    /** The emitter is strict: we control our own clock. */
    @Test
    fun `encoding refuses an implausible instant`() {
        // Apple-epoch seconds accidentally passed where millis belong.
        val appleSeconds = 791_692_800L
        try {
            CallPacket.encode(CallPacket.Type.CALL_REQUEST, appleSeconds)
            throw AssertionError("expected a refusal")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message!!.contains("MILLISECONDS"))
        }
    }

    // ============================================================== staleness

    /**
     * The two windows differ, and both are iOS's:
     * `maxCallSignalAgeSeconds = 30.0` (`:3589`) vs `max(that, 60.0)` (`:13640`).
     */
    @Test
    fun `an offer goes stale at thirty seconds and a terminal packet at sixty`() {
        val offer = CallPacket.decode(CallPacket.encode(CallPacket.Type.CALL_REQUEST, baseMs, ByteArray(40)))!!
        assertFalse(CallPacket.isStale(offer, baseMs + 30_000))
        assertTrue(CallPacket.isStale(offer, baseMs + 30_001))

        val end = CallPacket.decode(CallPacket.encode(CallPacket.Type.CALL_END, baseMs))!!
        assertFalse("a 45s-old hang-up must still silence a ringing phone", CallPacket.isStale(end, baseMs + 45_000))
        assertFalse(CallPacket.isStale(end, baseMs + 60_000))
        assertTrue(CallPacket.isStale(end, baseMs + 60_001))
    }

    /** No header instant means nothing to measure — refusing it would drop legacy offers. */
    @Test
    fun `a legacy offer is never stale`() {
        val legacy = CallPacket.decode(byteArrayOf(0x01) + CallOffer(key32(1), salt4(), callId).encode())!!
        assertFalse(CallPacket.isStale(legacy, baseMs + 10_000_000))
    }

    // ============================================================== the offer body

    /** `[sessionKey 32][salt 4][callId][cap][cap]` — `VoiceCallManager.swift:5936-5961`. */
    @Test
    fun `offer body is key then salt then callId then capability bytes`() {
        val body = CallOffer(key32(0x5A), salt4(), callId).encode()
        assertEquals(32 + 4 + callId.length + 2, body.size)
        assertArrayEquals(key32(0x5A), body.copyOfRange(0, 32))
        assertArrayEquals(salt4(), body.copyOfRange(32, 36))
        assertEquals(callId, String(body, 36, callId.length, Charsets.UTF_8))
        assertEquals("no capabilities claimed", 0, body[36 + callId.length].toInt())
        assertEquals(0, body[37 + callId.length].toInt())
    }

    /** Android emits two capability bytes (`EnhancedCallManager.kt:1413-1417`). */
    @Test
    fun `this client emits two capability bytes, matching Android`() {
        val body = CallOffer(key32(1), salt4(), callId).encode()
        assertEquals(36 + callId.length + 2, body.size)
    }

    /** The peel absorbs iOS's THREE-byte tail as readily as Android's two. */
    @Test
    fun `the peel recovers the callId from a two-byte and a three-byte capability tail`() {
        val head = key32(2) + salt4() + callId.toByteArray()

        val two = CallOffer.decode(head + byteArrayOf(0x01, 0x02))!!
        assertEquals(callId, two.callId)
        assertTrue(two.supportsOshiCodec)
        assertTrue(two.supports16kPcm)
        assertFalse(two.supportsAppleCodec)

        val three = CallOffer.decode(head + byteArrayOf(0x01, 0x02, 0x04))!!
        assertEquals("iOS's third byte must not be eaten as callId", callId, three.callId)
        assertTrue(three.supportsAppleCodec)
    }

    /**
     * A ZERO capability byte is present-and-false and still peels.
     *
     * This is why the loop tests `< 0x2D` and not `!= 0`. If a zero were left in place the
     * callId would gain a NUL, its SHA-256 would change, and every hole-punch packet would
     * be dropped as `cid_mismatch` — a call that signals and has no media
     * (`EnhancedCallManager.kt:2580-2588`).
     */
    @Test
    fun `a zero capability byte peels rather than joining the callId`() {
        val body = key32(3) + salt4() + callId.toByteArray() + byteArrayOf(0x00, 0x00)
        val offer = CallOffer.decode(body)!!
        assertEquals(callId, offer.callId)
        assertFalse(offer.callId.contains(' '))
    }

    /**
     * `0x2D` itself must NOT be peeled — the floor is `< 0x2D`, not `<= 0x2D`.
     *
     * **This test exists because the zero-byte test above turned out not to prove what it
     * claimed.** Mutating the peel condition from `< PEEL_FLOOR` to `!= 0` left that test
     * green: with the mutation the zero capability bytes are not stripped, the callId
     * keeps two trailing NULs — and `sanitizeCallId`'s control-character filter removes
     * them again, so the assertion passed while the peel was broken. It pinned the
     * sanitizer, not the peel.
     *
     * A `-` cannot be rescued that way: it is not a control character and not whitespace,
     * so if the peel eats it, it is gone. That makes this the assertion that actually
     * holds [CallOffer.PEEL_FLOOR] at its exact boundary value.
     */
    @Test
    fun `a callId ending in the peel floor byte keeps that byte`() {
        val endsInDash = "1B2C3D4E-5F60-7182-9394-A5B6C7D8E9F0-"
        val body = key32(8) + salt4() + endsInDash.toByteArray() + byteArrayOf(0x01, 0x02)
        val offer = CallOffer.decode(body)!!
        assertEquals("0x2D is the floor and must survive the peel", endsInDash, offer.callId)
        assertTrue(offer.supportsOshiCodec)
        assertTrue(offer.supports16kPcm)
    }

    /**
     * The peel never eats more than [CallOffer.MAX_CAP_BYTES], even when the callId's own
     * trailing bytes would qualify.
     *
     * The bound is what stops a runaway peel from silently shortening a callId — and a
     * shortened callId changes the SHA-256 the P2P layer derives from it, which is a call
     * that signals cleanly and then carries no media.
     */
    @Test
    fun `the peel strips at most three bytes`() {
        assertEquals(3, CallOffer.MAX_CAP_BYTES)
        val body = key32(9) + salt4() + callId.toByteArray() +
            byteArrayOf(0x01, 0x02, 0x04, 0x01, 0x02)
        val offer = CallOffer.decode(body)!!
        assertEquals(
            "two extra low bytes must stay in the callId rather than being eaten",
            callId + "",
            offer.callId + "",
        )
        assertTrue(offer.callId.startsWith("1B2C3D4E"))
    }

    /** `CallOfferCapabilities.kt:24` — the invariant, asserted from the emit side. */
    @Test
    fun `encoding refuses a callId containing a byte below the peel floor`() {
        try {
            CallOffer(key32(4), salt4(), "badid").encode()
            throw AssertionError("expected a refusal")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message!!.contains("0x2D"))
        }
    }

    /** iOS's `sanitizeCallId` strips whitespace/control rather than rejecting (`:13285`). */
    @Test
    fun `a callId with trailing whitespace is sanitized, not rejected`() {
        val body = key32(5) + salt4() + "$callId\n".toByteArray() + byteArrayOf(0x00, 0x00)
        assertEquals(callId, CallOffer.decode(body)!!.callId)
    }

    @Test
    fun `an offer body that is too short decodes to null`() {
        assertNull(CallOffer.decode(ByteArray(20)))
        assertNull(CallOffer.decode(key32(6) + salt4()))
    }

    // ============================================================== the accept body

    /** The accept carries NO callId — the fact behind RACE 3. */
    @Test
    fun `accept body is capability bytes only and carries no callId`() {
        val body = CallAccept().encode()
        assertEquals(2, body.size)
        assertFalse(
            "an accept must not contain the callId",
            String(body, Charsets.ISO_8859_1).contains("1B2C"),
        )
    }

    /**
     * An EMPTY accept is legal — a pre-negotiation build sends one.
     * Refusing it would make this client unable to complete a call with an older peer,
     * failing at 45 s with no diagnosis.
     */
    @Test
    fun `an empty accept body decodes to all capabilities false`() {
        val a = CallAccept.decode(ByteArray(0))
        assertFalse(a.supportsOshiCodec)
        assertFalse(a.supports16kPcm)
        assertFalse(a.supportsAppleCodec)
    }

    @Test
    fun `accept capability flags are read positionally`() {
        val a = CallAccept.decode(byteArrayOf(0x01, 0x02, 0x04))
        assertTrue(a.supportsOshiCodec)
        assertTrue(a.supports16kPcm)
        assertTrue(a.supportsAppleCodec)
    }

    // ============================================================== end reasons

    /** iOS's seven raw values, `VoiceCallManager.swift:1872-1893`. */
    @Test
    fun `end reason spellings are the shipped snake_case ones`() {
        assertEquals("hung_up", CallEndReason.HUNG_UP.wire)
        assertEquals("declined", CallEndReason.DECLINED.wire)
        assertEquals("no_answer", CallEndReason.NO_ANSWER.wire)
        assertEquals("network_error", CallEndReason.NETWORK_ERROR.wire)
        assertEquals("peer_disconnected", CallEndReason.PEER_DISCONNECTED.wire)
        assertEquals("connection_lost", CallEndReason.CONNECTION_LOST.wire)
        assertEquals("answered_elsewhere", CallEndReason.ANSWERED_ELSEWHERE.wire)
    }

    /** Accept iOS's extra spelling even though no Android emitter produces it. */
    @Test
    fun `the iOS-only peer_disconnected spelling is accepted`() {
        assertEquals(CallEndReason.PEER_DISCONNECTED, CallEndReason.fromWire("peer_disconnected"))
        assertNull(CallEndReason.fromWire("no_such_reason"))
    }

    // ============================================================== the outer envelope

    /**
     * Both spellings of both key names, and `payload`/`signal` twice.
     *
     * iOS reads `sender`/`signal`; Android reads either spelling. The shipped Android
     * emitter carries all four with the comment `// 🔧 iOS compatibility`, so dropping
     * one makes this client unreadable to one platform.
     */
    @Test
    fun `envelope carries both key spellings and duplicates the signal field`() {
        val env = CallSignalEnvelope(
            sender = "SENDERKEY", recipient = "RECIPKEY", signalBase64 = "AAEC",
            callId = callId, type = CallSignalType.CALL_REQUEST,
        )
        val o = JSONObject(env.encode(baseMs))
        assertEquals("SENDERKEY", o.getString("sender"))
        assertEquals("SENDERKEY", o.getString("senderPublicKey"))
        assertEquals("RECIPKEY", o.getString("recipient"))
        assertEquals("RECIPKEY", o.getString("recipientPublicKey"))
        assertEquals("AAEC", o.getString("payload"))
        assertEquals("AAEC", o.getString("signal"))
        assertEquals(callId, o.getString("callId"))
    }

    /**
     * The envelope `timestamp` is Unix SECONDS (epoch 3), while the packet header nine
     * bytes deeper is Unix MILLIS (epoch 2). Both fields are called `timestamp`.
     */
    @Test
    fun `envelope timestamp is unix seconds, not the header's millis`() {
        val env = CallSignalEnvelope("s", "r", "AAEC", callId, null)
        val o = JSONObject(env.encode(baseMs))
        assertEquals(1_770_000_000.0, o.getDouble("timestamp"), 0.0001)
        assertFalse(
            "millis here is the shipped Android bug, not the format",
            o.getDouble("timestamp") > 1e12,
        )
    }

    /** The desktop has no push (row 2.3), so it does not upload a display name. */
    @Test
    fun `envelope omits callerName`() {
        val o = JSONObject(CallSignalEnvelope("s", "r", "AAEC", callId, null).encode(baseMs))
        assertFalse("callerName is the one human identifier in this envelope", o.has("callerName"))
    }

    /** `VPSClient.kt:2464-2485` — accept every field-name variant the two clients emit. */
    @Test
    fun `envelope decodes both platforms' field names`() {
        val ios = CallSignalEnvelope.decode(
            """{"sender":"S","recipient":"R","signal":"AAEC","callId":"$callId","type":"callEnd"}""",
        )!!
        assertEquals("S", ios.sender)
        assertEquals("AAEC", ios.signalBase64)

        val android = CallSignalEnvelope.decode(
            """{"senderPublicKey":"S","recipientPublicKey":"R","payload":"AAEC","callId":"$callId"}""",
        )!!
        assertEquals("S", android.sender)
        assertEquals("AAEC", android.signalBase64)
    }

    /**
     * A MISSING type stays null here, deliberately unlike Android.
     *
     * Android defaults it to CALL_REQUEST (`VPSClient.kt:2470-2476`), which is safe there
     * only because the real type is re-read from byte 0 of the decrypted body. Keeping the
     * default without that would make every hintless envelope an incoming call.
     */
    @Test
    fun `a missing envelope type is null, never a defaulted call request`() {
        val e = CallSignalEnvelope.decode("""{"sender":"S","signal":"AAEC","callId":"x"}""")!!
        assertNull(e.type)
    }

    /** The server's terminal set, `call_server.js:666-667`, in both spellings. */
    @Test
    fun `terminal envelope hints are recognised in both platforms' spellings`() {
        assertTrue(CallSignalType.isTerminal("callEnd"))
        assertTrue(CallSignalType.isTerminal("callDeclined"))
        assertTrue(CallSignalType.isTerminal("callCancelled"))
        assertTrue(CallSignalType.isTerminal("call_end"))
        assertFalse(CallSignalType.isTerminal("callRequest"))
        assertFalse(CallSignalType.isTerminal(null))
    }

    // ============================================================== the seal

    /**
     * The KDF inputs, asserted as literals.
     *
     * These two strings are the entire interop contract for call signalling: get either
     * one wrong and every packet this client emits is undecryptable by both phones, with
     * no error anywhere — the peer's AEAD simply fails and the call never rings.
     */
    @Test
    fun `hkdf salt and info are the shipped literals`() {
        assertEquals("OSHI-VoiceCall-v1", CallSignalCrypto.HKDF_SALT)
        assertEquals("signaling", CallSignalCrypto.HKDF_INFO)
    }

    /**
     * The derivation is checked against a HAND-BUILT reference rather than against a
     * round trip through [CallSignalCrypto] itself.
     *
     * A seal-then-open test inside one implementation passes even if the salt is "banana",
     * because both halves use the same wrong value. This drives the primitives directly in
     * the order the Swift and Kotlin sources spell out, so a typo in either constant shows
     * up as a mismatch instead of as a green test.
     */
    @Test
    fun `signalling key is HKDF-SHA256 over the raw X25519 secret with the shipped salt and info`() {
        val a = OSHICryptoV2.generateX25519()
        val b = OSHICryptoV2.generateX25519()

        val expected = OSHICryptoV2.hkdf(
            ikm = OSHICryptoV2.dh(a.priv, b.pub),
            salt = "OSHI-VoiceCall-v1".toByteArray(),
            info = "signaling".toByteArray(),
            length = 32,
        )
        assertArrayEquals(expected, CallSignalCrypto.deriveKey(a.priv, b.pub))
    }

    /** Static-static: both sides derive the same key from opposite halves. */
    @Test
    fun `both peers derive the same signalling key`() {
        val a = OSHICryptoV2.generateX25519()
        val b = OSHICryptoV2.generateX25519()
        assertArrayEquals(
            CallSignalCrypto.deriveKey(a.priv, b.pub),
            CallSignalCrypto.deriveKey(b.priv, a.pub),
        )
    }

    /**
     * There is NO forward secrecy: the key is a pure function of the two identities, so
     * two calls a year apart are sealed under the same key.
     *
     * Asserted rather than merely documented, because `AUDIT_VOIP_TELECOM.md:78` claims
     * the opposite ("Double Ratchet forward secrecy") and a claim in a document is not
     * evidence. If someone later wires the ratchet in here, this test fails and they are
     * forced to update the doc comment that says calls have no forward secrecy.
     */
    @Test
    fun `the signalling key does not change between calls`() {
        val a = OSHICryptoV2.generateX25519()
        val b = OSHICryptoV2.generateX25519()
        assertArrayEquals(
            CallSignalCrypto.deriveKey(a.priv, b.pub),
            CallSignalCrypto.deriveKey(a.priv, b.pub),
        )
    }

    /** `nonce(12) ‖ ciphertext ‖ tag(16)` — CryptoKit's `.combined` layout. */
    @Test
    fun `sealed layout is nonce then ciphertext then tag`() {
        val a = OSHICryptoV2.generateX25519()
        val b = OSHICryptoV2.generateX25519()
        val packet = CallPacket.encode(CallPacket.Type.CALL_DECLINE, baseMs)
        val nonce = ByteArray(12) { it.toByte() }
        val sealed = CallSignalCrypto.seal(a.priv, b.pub, packet, nonce)

        assertEquals(12 + packet.size + 16, sealed.size)
        assertArrayEquals(nonce, sealed.copyOfRange(0, 12))
        assertArrayEquals(packet, CallSignalCrypto.open(b.priv, a.pub, sealed))
    }

    /** A tampered tag opens to null, never to a throw and never to plaintext. */
    @Test
    fun `a tampered sealed signal opens to null`() {
        val a = OSHICryptoV2.generateX25519()
        val b = OSHICryptoV2.generateX25519()
        val sealed = CallSignalCrypto.seal(a.priv, b.pub, CallPacket.encode(CallPacket.Type.CALL_END, baseMs))
        sealed[sealed.size - 1] = (sealed[sealed.size - 1].toInt() xor 0xFF).toByte()
        assertNull(CallSignalCrypto.open(b.priv, a.pub, sealed))
    }

    /** A third party's key does not open it — this is the only authentication in the path. */
    @Test
    fun `a signal sealed for one peer does not open for another`() {
        val a = OSHICryptoV2.generateX25519()
        val b = OSHICryptoV2.generateX25519()
        val c = OSHICryptoV2.generateX25519()
        val sealed = CallSignalCrypto.seal(a.priv, b.pub, CallPacket.encode(CallPacket.Type.CALL_END, baseMs))
        assertNull(CallSignalCrypto.open(c.priv, a.pub, sealed))
    }

    /** Too short to contain a nonce and a tag: refused before the cipher sees it. */
    @Test
    fun `a truncated sealed signal opens to null without throwing`() {
        val a = OSHICryptoV2.generateX25519()
        val b = OSHICryptoV2.generateX25519()
        assertNull(CallSignalCrypto.open(a.priv, b.pub, ByteArray(27)))
        assertNull(CallSignalCrypto.open(a.priv, b.pub, ByteArray(0)))
    }

    /** End to end: seal an offer, open it, and recover the media key. */
    @Test
    fun `an offer survives a full seal, envelope, decode and open`() {
        val caller = OSHICryptoV2.generateX25519()
        val callee = OSHICryptoV2.generateX25519()
        val mediaKey = key32(0x7E)

        val packet = CallPacket.encode(
            CallPacket.Type.CALL_REQUEST, baseMs,
            CallOffer(mediaKey, salt4(), callId).encode(),
        )
        val sealed = CallSignalCrypto.seal(caller.priv, callee.pub, packet)
        val wire = CallSignalEnvelope(
            sender = "S", recipient = "R",
            signalBase64 = Base64.getEncoder().encodeToString(sealed),
            callId = callId, type = CallSignalType.CALL_REQUEST,
        ).encode(baseMs)

        val env = CallSignalEnvelope.decode(wire)!!
        val opened = CallSignalCrypto.open(callee.priv, caller.pub, env.signalBytes()!!)!!
        val decoded = CallPacket.decode(opened)!!
        val offer = CallOffer.decode(decoded.payload)!!

        assertEquals(CallPacket.Type.CALL_REQUEST, decoded.type)
        assertEquals(callId, offer.callId)
        assertArrayEquals("the media key must survive the whole path", mediaKey, offer.sessionKey)
    }
}
