package com.oshi.messenger.network.v2.devsync

import org.json.JSONArray
import org.json.JSONObject
import java.io.File

/**
 * Checks THIS implementation against the golden vectors in docs/fixtures/devsync/ (generated by the
 * independent Python reference, devsync_ref.py). Shared by the Android and Desktop unit tests so both
 * platforms run the identical check; the iOS implementation runs the same files.
 *
 * Returns one line per check; failures start with "FAIL".
 */
object DevSyncVectorCheck {

    class Report {
        val lines = ArrayList<String>()
        var failures = 0
        var passes = 0
        fun eq(what: String, expected: Any?, actual: Any?) {
            if (expected == actual) { passes++ } else { failures++; lines += "FAIL $what: expected <$expected> got <$actual>" }
        }
        fun ok(what: String, cond: Boolean) { if (cond) passes++ else { failures++; lines += "FAIL $what" } }
        override fun toString() = "passes=$passes failures=$failures\n" + lines.joinToString("\n")
    }

    private fun h(s: String) = DevSyncCrypto.unhex(s)
    private fun x(b: ByteArray) = DevSyncCrypto.hex(b)

    /** Walk up from [start] to find docs/fixtures/devsync. */
    fun locate(start: File = File(System.getProperty("user.dir")).absoluteFile): File {
        var d: File? = start
        while (d != null) {
            val f = File(d, "docs/fixtures/devsync")
            if (File(f, "keys.json").isFile) return f
            d = d.parentFile
        }
        error("docs/fixtures/devsync not found above $start")
    }

    fun runAll(dir: File = locate()): Report {
        val r = Report()
        keys(JSONObject(File(dir, "keys.json").readText()), r)
        handshake(JSONObject(File(dir, "noise_handshake.json").readText()), r)
        transport(JSONObject(File(dir, "noise_transport.json").readText()), JSONObject(File(dir, "noise_handshake.json").readText()), r)
        framing(JSONObject(File(dir, "framing.json").readText()), r)
        diff(JSONObject(File(dir, "diff.json").readText()), r)
        merge(JSONObject(File(dir, "merge.json").readText()), r)
        relayAuth(JSONObject(File(dir, "relay_auth.json").readText()), r)
        return r
    }

    /** The vector devices' dsk: Ed25519 public of SHA-256("OSHI-DEVSYNC vector dsk" ‖ dk_priv), std base64. */
    private fun dskOfStatic(dkPrivHex: String): String =
        DevSyncRelayAuth.b64(DevSyncRelayAuth.ed25519Public(DevSyncCrypto.sha256("OSHI-DEVSYNC vector dsk".toByteArray(), h(dkPrivHex))))

    // ------------------------------------------------------------------ relay upgrade auth

    /** __DEVSYNC_DEVICE_AUTH_2026_09_23__ relay_auth.json: B, both strings, both signatures, the header set. */
    fun relayAuth(v: JSONObject, r: Report) {
        val cases = v.getJSONArray("cases")
        val accountSigs = HashSet<String>()
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            val n = c.getString("name")
            val inp = c.getJSONObject("inputs")
            val creds = SeedRelayDeviceCredentials(h(inp.getString("dkPub")), h(inp.getString("dskSeed")))
            val accountSeed = h(inp.getString("accountSigningSeed"))
            val ts = inp.getString("ts")
            val identity = inp.getString("identity")
            val deviceId = DevSyncKeys.deviceIdHex(creds.dkPub)
            r.eq("$n deviceId", c.getString("deviceId"), deviceId)
            r.eq("$n dsk", c.getString("dsk"), DevSyncRelayAuth.b64(creds.dskPub))
            val binding = DevSyncRelayAuth.bindingString(identity, deviceId, DevSyncRelayAuth.b64(creds.dkPub), DevSyncRelayAuth.b64(creds.dskPub), inp.getString("nonce"))
            r.eq("$n binding", c.getString("binding"), binding)
            val bh = x(DevSyncCrypto.sha256(binding.toByteArray(Charsets.UTF_8)))
            r.eq("$n bindingSha256", c.getString("bindingSha256"), bh)
            r.eq("$n deviceString", c.getString("deviceString"), DevSyncRelayAuth.deviceString(deviceId, bh, ts))
            // The account half through the same seam the platforms use: a signer handed B as the body.
            var accountString: String? = null
            val headers = DevSyncRelayAuth.upgradeHeaders(identity, deviceId, creds, { body ->
                val canon = "GET\n${RelayConnector.PATH}\n${x(DevSyncCrypto.sha256(body))}\n$ts"
                accountString = canon
                linkedMapOf(
                    "x-oshi-signature" to DevSyncRelayAuth.b64(DevSyncRelayAuth.ed25519Sign(accountSeed, canon.toByteArray(Charsets.UTF_8))),
                    "x-oshi-timestamp" to ts,
                    "x-oshi-signing-pubkey" to DevSyncRelayAuth.b64(DevSyncRelayAuth.ed25519Public(accountSeed)),
                    "x-oshi-user" to identity,
                )
            }, inp.getString("nonce"))
            r.eq("$n accountString", c.getString("accountString"), accountString)
            val want = c.getJSONObject("headers")
            r.eq("$n header count", want.length(), headers.size)
            for (k in want.keys()) r.eq("$n header $k", want.getString(k), headers[k])
            r.ok("$n device signature verifies", DevSyncRelayAuth.ed25519Verify(creds.dskPub,
                c.getString("deviceString").toByteArray(Charsets.UTF_8), java.util.Base64.getDecoder().decode(c.getString("deviceSignature"))))
            accountSigs += c.getString("accountSignature")
        }
        r.ok("same-millisecond upgrades never share an account signature", accountSigs.size == cases.length())
        r.eq("normalizeIdentity base64url", "ERERERERERERERERERERERERERERERERERERERERERE=",
            DevSyncRelayAuth.normalizeIdentity("ERERERERERERERERERERERERERERERERERERERERERE"))
        r.eq("normalizeIdentity percent", "+/+/ERERERERERERERERERERERERERERERERERERERE=",
            DevSyncRelayAuth.normalizeIdentity("%2B%2f-_ERERERERERERERERERERERERERERERERERERERE%3D"))
    }

    // ------------------------------------------------------------------ keys

    fun keys(v: JSONObject, r: Report) {
        val acc = v.getJSONObject("account")
        val ik = h(acc.getString("ikPriv"))
        r.eq("ikPub", acc.getString("ikPub"), x(DevSyncCrypto.x25519Public(ik)))
        r.eq("psk", acc.getString("psk"), x(DevSyncKeys.psk(ik)))
        r.eq("disc", acc.getString("disc"), x(DevSyncKeys.disc(ik)))
        val other = v.getJSONObject("otherAccount")
        r.eq("other psk", other.getString("psk"), x(DevSyncKeys.psk(h(other.getString("ikPriv")))))
        val devs = v.getJSONObject("devices")
        for (name in listOf("A", "B", "C")) {
            val d = devs.getJSONObject(name)
            val pub = DevSyncCrypto.x25519Public(h(d.getString("priv")))
            r.eq("device $name pub", d.getString("pub"), x(pub))
            r.eq("device $name id", d.getString("deviceId"), DevSyncKeys.deviceIdHex(pub))
            r.eq("device $name dsk", d.getString("dsk"), DevSyncRelayAuth.b64(DevSyncRelayAuth.ed25519Public(h(d.getString("dskSeed")))))
            r.eq("device $name dskSeed", d.getString("dskSeed"), x(DevSyncCrypto.sha256("OSHI-DEVSYNC vector dsk".toByteArray(), h(d.getString("priv")))))
        }
        val disc = DevSyncKeys.disc(ik)
        val tags = v.getJSONArray("mdnsTags")
        for (i in 0 until tags.length()) {
            val t = tags.getJSONObject(i)
            r.eq("mdnsTag ${t.getLong("unixSeconds")}", t.getString("tag"), DevSyncKeys.mdnsTag(disc, t.getLong("unixSeconds")))
        }
        val sas = v.getJSONArray("sas")
        for (i in 0 until sas.length()) {
            val s = sas.getJSONObject(i)
            r.eq("sas[$i]", s.getString("code"), DevSyncKeys.sasCode(h(s.getString("handshakeHash"))))
        }
    }

    // ------------------------------------------------------------------ handshake

    private class Run(val init: NoiseHandshake, val resp: NoiseHandshake)

    fun handshake(v: JSONObject, r: Report) {
        r.eq("protocolName", v.getString("protocolName"), String(Noise.PROTOCOL_NAME, Charsets.US_ASCII))
        val cases = v.getJSONArray("cases")
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            val name = c.getString("name")
            val prologueI = h(c.getString("prologue"))
            val prologueR = if (c.has("responderPrologue")) h(c.getString("responderPrologue")) else prologueI
            val psk = h(c.getString("psk"))
            val pskR = if (c.has("responderPsk")) h(c.getString("responderPsk")) else psk
            // The prologue this implementation derives for a well-formed case must equal the vector's.
            if (name == "relay" || name == "lan") {
                val idI = DevSyncKeys.deviceId(DevSyncCrypto.x25519Public(h(c.getString("initiatorStaticPriv"))))
                val idR = DevSyncKeys.deviceId(DevSyncCrypto.x25519Public(h(c.getString("responderStaticPriv"))))
                r.eq("$name prologue", c.getString("prologue"), x(DevSyncKeys.prologue(c.getString("transport"), idI, idR)))
                if (name == "relay") r.ok("$name: smaller id initiates", DevSyncKeys.compareUnsigned(idI, idR) < 0)
            }
            val init = NoiseHandshake(true, h(c.getString("initiatorStaticPriv")), psk, prologueI, h(c.getString("initiatorEphemeralPriv")))
            val resp = NoiseHandshake(false, h(c.getString("responderStaticPriv")), pskR, prologueR, h(c.getString("responderEphemeralPriv")))
            val m1 = c.getJSONObject("msg1")
            val w1 = init.writeMessage1(h(m1.getString("payload")))
            r.eq("$name msg1", m1.getString("message"), x(w1))
            r.eq("$name h after msg1", m1.getString("hAfter"), x(init.handshakeHash))
            if (c.has("responderResult")) {
                val rejected = try { resp.readMessage1(w1); false } catch (e: NoiseException) { true }
                r.ok("$name: responder rejects message 1", rejected)
                continue
            }
            r.eq("$name msg1 payload", m1.getString("payload"), x(resp.readMessage1(w1)))
            val m2 = c.getJSONObject("msg2")
            val w2 = resp.writeMessage2(h(m2.getString("payload")))
            r.eq("$name msg2", m2.getString("message"), x(w2))
            r.eq("$name h after msg2", m2.getString("hAfter"), x(resp.handshakeHash))
            r.eq("$name msg2 payload", m2.getString("payload"), x(init.readMessage2(w2)))
            val m3 = c.getJSONObject("msg3")
            val w3 = init.writeMessage3(h(m3.getString("payload")))
            r.eq("$name msg3", m3.getString("message"), x(w3))
            r.eq("$name h after msg3", m3.getString("hAfter"), x(init.handshakeHash))
            r.eq("$name msg3 payload", m3.getString("payload"), x(resp.readMessage3(w3)))
            r.eq("$name handshakeHash", c.getString("handshakeHash"), x(resp.handshakeHash))
            r.eq("$name sas", c.getString("sasCode"), DevSyncKeys.sasCode(init.handshakeHash))
            val (iSend, _) = init.split()
            val (rSend, _) = resp.split()
            r.eq("$name i->r key", c.getString("initiatorToResponderKey"), iSend.keyForTest()?.let(::x))
            r.eq("$name r->i key", c.getString("responderToInitiatorKey"), rSend.keyForTest()?.let(::x))
            // HELLO payloads decode, and the deviceId they carry is H(static) — the §4.1 check.
            val helloR = Hello.decode(h(m2.getString("payload")))
            r.eq("$name responder HELLO id", DevSyncKeys.deviceIdHex(init.remoteStatic!!), helloR?.deviceId)
            val helloI = Hello.decode(h(m3.getString("payload")))
            r.eq("$name initiator HELLO id", DevSyncKeys.deviceIdHex(resp.remoteStatic!!), helloI?.deviceId)
            // __DEVSYNC_DEVICE_AUTH_2026_09_23__ HELLO carries the sender's dsk (keys.json devices.*.dsk).
            r.eq("$name responder HELLO dsk", dskOfStatic(c.getString("responderStaticPriv")), helloR?.dsk)
            r.eq("$name initiator HELLO dsk", dskOfStatic(c.getString("initiatorStaticPriv")), helloI?.dsk)
        }
    }

    // ------------------------------------------------------------------ transport

    fun transport(v: JSONObject, hsVectors: JSONObject, r: Report) {
        val cases = hsVectors.getJSONArray("cases")
        var lan: JSONObject? = null
        for (i in 0 until cases.length()) if (cases.getJSONObject(i).getString("name") == v.getString("fromHandshake")) lan = cases.getJSONObject(i)
        val c = lan!!
        val init = NoiseHandshake(true, h(c.getString("initiatorStaticPriv")), h(c.getString("psk")), h(c.getString("prologue")), h(c.getString("initiatorEphemeralPriv")))
        val resp = NoiseHandshake(false, h(c.getString("responderStaticPriv")), h(c.getString("psk")), h(c.getString("prologue")), h(c.getString("responderEphemeralPriv")))
        resp.readMessage1(init.writeMessage1(h(c.getJSONObject("msg1").getString("payload"))))
        init.readMessage2(resp.writeMessage2(h(c.getJSONObject("msg2").getString("payload"))))
        resp.readMessage3(init.writeMessage3(h(c.getJSONObject("msg3").getString("payload"))))
        val (iSend, iRecv) = init.split()
        val (rSend, rRecv) = resp.split()
        val i2r = v.getJSONArray("initiatorToResponder")
        for (k in 0 until i2r.length()) {
            val m = i2r.getJSONObject(k)
            val ct = iSend.encrypt(h(m.getString("plaintext")))
            r.eq("i->r[$k]", m.getString("ciphertext"), x(ct))
            r.eq("i->r[$k] decrypt", m.getString("plaintext"), x(rRecv.decrypt(ct)))
        }
        val r2i = v.getJSONArray("responderToInitiator")
        for (k in 0 until r2i.length()) {
            val m = r2i.getJSONObject(k)
            val ct = rSend.encrypt(h(m.getString("plaintext")))
            r.eq("r->i[$k]", m.getString("ciphertext"), x(ct))
            r.eq("r->i[$k] decrypt", m.getString("plaintext"), x(iRecv.decrypt(ct)))
        }
        val rf = v.getJSONObject("rekeyFunction")
        val cs = CipherState(h(rf.getString("keyBefore")))
        cs.rekey()
        r.eq("Rekey()", rf.getString("keyAfter"), cs.keyCopy()?.let(::x))
        for (name in listOf("rekeyByMessages", "rekeyByBytes")) {
            val o = v.getJSONObject(name)
            val pol = o.getJSONObject("policy")
            val tc = TransportCipher(CipherState(h(o.getString("initialKey"))), pol.getLong("maxMessages"), pol.getLong("maxBytes"))
            val rx = TransportCipher(CipherState(h(o.getString("initialKey"))), pol.getLong("maxMessages"), pol.getLong("maxBytes"))
            val msgs = o.getJSONArray("messages")
            for (k in 0 until msgs.length()) {
                val m = msgs.getJSONObject(k)
                r.eq("$name[$k] key used", m.getString("keyUsed"), tc.keyForTest()?.let(::x))
                val ct = tc.encrypt(h(m.getString("plaintext")))
                r.eq("$name[$k] ciphertext", m.getString("ciphertext"), x(ct))
                r.eq("$name[$k] key after", m.getString("keyAfter"), tc.keyForTest()?.let(::x))
                r.eq("$name[$k] receiver decrypts", m.getString("plaintext"), x(rx.decrypt(ct)))
            }
        }
    }

    // ------------------------------------------------------------------ framing

    fun framing(v: JSONObject, r: Report) {
        val recs = v.getJSONArray("records")
        for (i in 0 until recs.length()) {
            val o = recs.getJSONObject(i)
            val enc = DevSyncWire.encodeRecord(o.getInt("type"), o.getInt("flags"), o.getLong("seq"), o.getString("body").toByteArray(Charsets.UTF_8))
            r.eq("record[$i]", o.getString("bytes"), x(enc))
            val dec = DevSyncWire.decodeRecord(enc)
            r.ok("record[$i] roundtrip", dec.type == o.getInt("type") && dec.seq == o.getLong("seq") && String(dec.body, Charsets.UTF_8) == o.getString("body"))
        }
        val lan = v.getJSONObject("lanFrame")
        r.eq("lanFrame", lan.getString("bytes"), x(DevSyncWire.lanFrame(h(lan.getString("noise")))))
        r.eq("lanFrame read", lan.getString("noise"), x(DevSyncWire.readLanFrame(h(lan.getString("bytes")).inputStream())))
        val out = v.getJSONObject("relayOutbound")
        r.eq("relayOutbound", out.getString("bytes"), x(DevSyncWire.relayFrame(h(out.getString("destination")), out.getInt("kind"), h(out.getString("noise")))))
        val inb = v.getJSONObject("relayInbound")
        val parsed = DevSyncWire.parseRelayFrame(h(inb.getString("bytes")))
        r.eq("relayInbound source", inb.getString("source"), parsed?.deviceIdHex)
        r.eq("relayInbound kind", inb.getInt("kind"), parsed?.kind)
        r.eq("relayInbound noise", inb.getString("noise"), parsed?.noise?.let(::x))
        val mc = v.getJSONObject("mediaChunk")
        val body = DevSyncWire.encodeMediaChunk(h(mc.getString("sha256")), mc.getLong("offset"), mc.getBoolean("last"), h(mc.getString("data")))
        r.eq("mediaChunk body", mc.getString("body"), x(body))
        r.eq("mediaChunk record", mc.getString("record"), x(DevSyncWire.encodeRecord(DevSyncWire.MEDIA_CHUNK, 0, 9, body)))
        val lim = v.getJSONObject("limits")
        r.eq("maxRecordPlaintext", lim.getInt("maxRecordPlaintext"), DevSyncWire.MAX_RECORD)
        r.eq("maxMediaChunkData", lim.getInt("maxMediaChunkData"), DevSyncWire.MEDIA_CHUNK_DATA)
    }

    // ------------------------------------------------------------------ diff

    private fun parseMessages(convs: Map<String, SyncConversation>, arr: JSONArray): List<SyncMessage> =
        (0 until arr.length()).map { i ->
            val o = arr.getJSONObject(i)
            SyncCodec.messageFromJson(o, convs.getValue(o.getString("conversation")))!!
        }

    fun diff(v: JSONObject, r: Report) {
        val convs = LinkedHashMap<String, SyncConversation>()
        val ca = v.getJSONArray("conversations")
        for (i in 0 until ca.length()) SyncCodec.conversationFromJson(ca.getJSONObject(i))!!.let { convs[it.id] = it }
        val revs = v.getJSONArray("revs")
        for (i in 0 until revs.length()) {
            val o = revs.getJSONObject(i)
            val m = o.getJSONObject("message")
            val msg = SyncCodec.messageFromJson(m, convs.getValue(m.getString("conversation")))!!
            r.eq("canonical ${o.getString("id")}", o.getString("canonical"), SyncCodec.canonicalRev(msg))
            r.eq("rev ${o.getString("id")}", o.getString("rev"), SyncCodec.rev(msg))
            // The codec round-trips the object without changing its rev.
            val again = SyncCodec.messageFromJson(SyncCodec.messageToJson(msg), convs.getValue(msg.conversation))!!
            r.eq("rev roundtrip ${o.getString("id")}", o.getString("rev"), SyncCodec.rev(again))
        }
        val sides = HashMap<String, List<SyncMessage>>()
        for (side in listOf("deviceA", "deviceB")) {
            val s = v.getJSONObject(side)
            val msgs = parseMessages(convs, s.getJSONArray("messages"))
            sides[side] = msgs
            val byConv = msgs.groupBy { it.conversation }
            val summary = s.getJSONArray("summary")
            for (i in 0 until summary.length()) {
                val e = summary.getJSONObject(i)
                val ms = byConv.getValue(e.getString("id"))
                r.eq("$side summary count ${e.getString("id")}", e.getInt("count"), ms.size)
                r.eq("$side summary newest", e.getString("newest"), SyncJson.iso(ms.maxOf { it.timestampMs }))
                r.eq("$side summary digest ${e.getString("id")}", e.getString("digest"), SyncCodec.digest(ms.map { it.id to SyncCodec.rev(it) }))
            }
            val buckets = s.getJSONObject("buckets")
            for (cid in buckets.keys()) {
                val arr = buckets.getJSONArray(cid)
                val byDay = byConv.getValue(cid).groupBy { SyncJson.utcDay(it.timestampMs) }
                for (i in 0 until arr.length()) {
                    val b = arr.getJSONObject(i)
                    val ms = byDay.getValue(b.getString("day"))
                    r.eq("$side bucket $cid ${b.getString("day")}", b.getString("digest"), SyncCodec.digest(ms.map { it.id to SyncCodec.rev(it) }))
                }
            }
        }
        fun wants(mine: List<SyncMessage>, theirs: List<SyncMessage>): List<String> {
            val have = mine.associate { it.idKey to SyncCodec.rev(it) }
            return theirs.filter { have[it.idKey] != SyncCodec.rev(it) }.map { it.id }
                .sortedWith { a, b -> CanonicalJson.UTF8_ORDER.compare(SyncJson.asciiLower(a), SyncJson.asciiLower(b)) }
        }
        val exp = v.getJSONObject("expected")
        r.eq("aWantsFromB", exp.getJSONArray("aWantsFromB").toString(), JSONArray(wants(sides.getValue("deviceA"), sides.getValue("deviceB"))).toString())
        r.eq("bWantsFromA", exp.getJSONArray("bWantsFromA").toString(), JSONArray(wants(sides.getValue("deviceB"), sides.getValue("deviceA"))).toString())
        val a = sides.getValue("deviceA").first { it.idKey == "edit-1" }
        val b = sides.getValue("deviceB").first { it.idKey == "edit-1" }
        val merged = SyncMerge.message(a, b)
        val mergedExp = exp.getJSONObject("mergedEdit1")
        r.eq("mergedEdit1", SyncCodec.messageFromJson(mergedExp, convs.getValue(mergedExp.getString("conversation"))), merged)
        r.eq("mergedEdit1Rev", exp.getString("mergedEdit1Rev"), SyncCodec.rev(merged))
        r.eq("merge commutes (rev)", SyncCodec.rev(merged), SyncCodec.rev(SyncMerge.message(b, a)))
    }

    // ------------------------------------------------------------------ merge

    fun merge(v: JSONObject, r: Report) {
        val cases = v.getJSONArray("messages")
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            val name = c.getString("name")
            val lj = c.getJSONObject("local")
            val conv = SyncConversation.direct(lj.getString("conversation").removePrefix("direct:"))
            val local = SyncCodec.messageFromJson(lj, conv)!!
            val remote = SyncCodec.messageFromJson(c.getJSONObject("remote"), conv)!!
            val expected = SyncCodec.messageFromJson(c.getJSONObject("merged"), conv)!!
            val got = SyncMerge.message(local, remote)
            r.eq("merge $name", expected, got)
            r.eq("merge $name rev", c.getString("mergedRev"), SyncCodec.rev(got))
            r.eq("merge $name commutes", SyncCodec.rev(got), SyncCodec.rev(SyncMerge.message(remote, local)))
            r.eq("merge $name idempotent", got, SyncMerge.message(got, remote))
        }
        val contacts = v.getJSONArray("contacts")
        for (i in 0 until contacts.length()) {
            val c = contacts.getJSONObject(i)
            val got = SyncMerge.contact(SyncContact.fromJson(c.getJSONObject("local"))!!, SyncContact.fromJson(c.getJSONObject("remote"))!!)
            r.eq("contact ${c.getString("name")}", SyncContact.fromJson(c.getJSONObject("merged")), got)
        }
        val profile = v.getJSONArray("profile")
        for (i in 0 until profile.length()) {
            val p = profile.getJSONObject(i)
            val got = SyncMerge.profile(SyncProfile.fromJson(p.getJSONObject("local")), SyncProfile.fromJson(p.getJSONObject("remote")))
            val exp = SyncProfile.fromJson(p.getJSONObject("merged"))
            r.eq("profile[$i]", exp?.name to exp?.updatedAtMs, got?.name to got?.updatedAtMs)
        }
        val rs = v.getJSONArray("readState")
        for (i in 0 until rs.length()) {
            val p = rs.getJSONObject(i)
            val got = SyncMerge.readState(SyncReadState.fromJson(p.getJSONObject("local"))!!, SyncReadState.fromJson(p.getJSONObject("remote"))!!)
            r.eq("readState[$i]", SyncReadState.fromJson(p.getJSONObject("merged")), got)
        }
        val groups = v.getJSONArray("groups")
        for (i in 0 until groups.length()) {
            val g = groups.getJSONObject(i)
            val local = if (g.isNull("local")) null else SyncGroup.fromJson(g.getJSONObject("local"))
            val remote = SyncGroup.fromJson(g.getJSONObject("remote"))!!
            val got = SyncMerge.group(local, remote)
            r.eq("group ${g.getString("name")}", g.getString("canonical"), got.canonicalJson())
            r.eq("group ${g.getString("name")} parses", g.getString("canonical"), SyncGroup.fromJson(g.getJSONObject("merged"))!!.canonicalJson())
            if (local != null) r.eq("group ${g.getString("name")} commutes", got.canonicalJson(), SyncMerge.group(remote, local).canonicalJson())
        }
        val dev = v.getJSONObject("devices")
        val self = dev.getString("selfDeviceId")
        val reg = LinkedDeviceRegistry(InMemoryStateStore(), self)
        // Seed "local": the vector's local list is exactly device B, approved earlier.
        val steps = dev.getJSONArray("steps")
        val bEntry = LinkedDevice.fromJson(steps.getJSONObject(2).getJSONObject("record").getJSONArray("linked").getJSONObject(0))!!
        reg.link(bEntry)
        r.eq("devices local", dev.getJSONObject("local").getJSONArray("linked").toString(), JSONArray(reg.linked().map { it.deviceId }.sorted()).toString())
        for (i in 0 until steps.length()) {
            val s = steps.getJSONObject(i)
            reg.mergeDevicesRecord(DevicesRecord.fromJson(s.getJSONObject("record")), "peer")
            val after = s.getJSONObject("after")
            r.eq("devices step $i linked", after.getJSONArray("linked").toString(), JSONArray(reg.linked().map { it.deviceId }.sorted()).toString())
            r.eq("devices step $i revoked", after.getJSONArray("revoked").toString(), JSONArray(reg.revoked().sorted()).toString())
        }
    }
}
