package com.oshi.messenger.network.v2.devsync

import org.bouncycastle.crypto.InvalidCipherTextException
import org.bouncycastle.crypto.agreement.X25519Agreement
import org.bouncycastle.crypto.modes.ChaCha20Poly1305
import org.bouncycastle.crypto.params.AEADParameters
import org.bouncycastle.crypto.params.KeyParameter
import org.bouncycastle.crypto.params.X25519PrivateKeyParameters
import org.bouncycastle.crypto.params.X25519PublicKeyParameters
import java.security.MessageDigest
import java.security.SecureRandom
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec

/**
 * __DEVSYNC_DIRECT_2026_09_22__ Primitives for own-device sync (docs/OSHI_DEVICE_SYNC_DIRECT.md).
 *
 * PURE JVM (BouncyCastle + javax.crypto, no android.*): compiled by Android AND by OSHI-Desktop
 * (see the allowlist in OSHI-Desktop/build.gradle.kts). Checked byte-for-byte against the golden
 * vectors in docs/fixtures/devsync/, which were generated by an independent Python implementation
 * (pyca/cryptography) — see that directory's README.
 */
object DevSyncCrypto {

    private val rng = SecureRandom()

    fun randomBytes(n: Int): ByteArray = ByteArray(n).also { rng.nextBytes(it) }

    fun sha256(vararg parts: ByteArray): ByteArray {
        val md = MessageDigest.getInstance("SHA-256")
        for (p in parts) md.update(p)
        return md.digest()
    }

    fun hmacSha256(key: ByteArray, vararg data: ByteArray): ByteArray {
        val mac = Mac.getInstance("HmacSHA256")
        // javax.crypto refuses an empty key; HMAC defines it as zero bytes, which pads identically.
        mac.init(SecretKeySpec(if (key.isEmpty()) ByteArray(32) else key, "HmacSHA256"))
        for (d in data) mac.update(d)
        return mac.doFinal()
    }

    /** RFC 5869 HKDF-SHA256. An empty salt means 32 zero bytes (RFC 5869 §2.2). */
    fun hkdf(ikm: ByteArray, salt: ByteArray, info: ByteArray, length: Int): ByteArray {
        require(length in 1..255 * 32)
        val prk = hmacSha256(if (salt.isEmpty()) ByteArray(32) else salt, ikm)
        val out = ByteArray(length)
        var t = ByteArray(0)
        var pos = 0
        var i = 1
        while (pos < length) {
            t = hmacSha256(prk, t, info, byteArrayOf(i.toByte()))
            val n = minOf(t.size, length - pos)
            System.arraycopy(t, 0, out, pos, n)
            pos += n
            i++
        }
        return out
    }

    fun x25519Public(priv: ByteArray): ByteArray {
        require(priv.size == 32) { "X25519 private key must be 32 bytes" }
        return X25519PrivateKeyParameters(priv, 0).generatePublicKey().encoded
    }

    /** X25519 DH. Throws [NoiseException] on an all-zero result (low-order peer key). */
    fun x25519(priv: ByteArray, pub: ByteArray): ByteArray {
        require(priv.size == 32 && pub.size == 32)
        val agreement = X25519Agreement()
        agreement.init(X25519PrivateKeyParameters(priv, 0))
        val out = ByteArray(32)
        try {
            agreement.calculateAgreement(X25519PublicKeyParameters(pub, 0), out, 0)
        } catch (e: IllegalStateException) {
            throw NoiseException("X25519 agreement failed (low-order point)")
        }
        return out
    }

    fun generateX25519Private(): ByteArray = randomBytes(32)

    /** Noise ChaChaPoly nonce: 4 zero bytes followed by the 64-bit counter, LITTLE-endian. */
    private fun noiseNonce(n: Long): ByteArray {
        val nonce = ByteArray(12)
        var v = n
        for (i in 0 until 8) {
            nonce[4 + i] = (v and 0xFF).toByte()
            v = v ushr 8
        }
        return nonce
    }

    fun chachaEncrypt(key: ByteArray, n: Long, ad: ByteArray, plaintext: ByteArray): ByteArray {
        val c = ChaCha20Poly1305()
        c.init(true, AEADParameters(KeyParameter(key), 128, noiseNonce(n), ad))
        val out = ByteArray(c.getOutputSize(plaintext.size))
        var len = c.processBytes(plaintext, 0, plaintext.size, out, 0)
        len += c.doFinal(out, len)
        return if (len == out.size) out else out.copyOf(len)
    }

    fun chachaDecrypt(key: ByteArray, n: Long, ad: ByteArray, ciphertext: ByteArray): ByteArray {
        if (ciphertext.size < 16) throw NoiseException("ciphertext shorter than the tag")
        val c = ChaCha20Poly1305()
        c.init(false, AEADParameters(KeyParameter(key), 128, noiseNonce(n), ad))
        val out = ByteArray(c.getOutputSize(ciphertext.size))
        try {
            var len = c.processBytes(ciphertext, 0, ciphertext.size, out, 0)
            len += c.doFinal(out, len)
            return if (len == out.size) out else out.copyOf(len)
        } catch (e: InvalidCipherTextException) {
            throw NoiseException("authentication failed")
        }
    }

    fun constantTimeEquals(a: ByteArray, b: ByteArray): Boolean = MessageDigest.isEqual(a, b)

    fun hex(b: ByteArray): String {
        val sb = StringBuilder(b.size * 2)
        for (x in b) {
            val v = x.toInt() and 0xFF
            sb.append(HEX[v ushr 4]).append(HEX[v and 0x0F])
        }
        return sb.toString()
    }

    fun unhex(s: String): ByteArray {
        require(s.length % 2 == 0) { "odd hex length" }
        return ByteArray(s.length / 2) { i ->
            ((Character.digit(s[2 * i], 16) shl 4) or Character.digit(s[2 * i + 1], 16)).toByte()
        }
    }

    private val HEX = "0123456789abcdef".toCharArray()
}

class NoiseException(message: String) : Exception(message)
