package com.oshi.desktop.pairing

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.util.Base64

/**
 * [ContactQr] against the strings the shipped phones actually produce.
 *
 * Every literal below was lifted from `OSHI/` or `OSHI-Android/`, never generated by the
 * code under test — a test whose fixture comes out of its own encoder proves the encoder
 * is self-consistent and nothing else. The key used throughout is iOS's own preview
 * constant (`QRCodeDisplayView.swift:334`), which is a real 32-byte X25519 key and, more
 * usefully, one that happens to contain a `/`, a `+` and a `=`: exactly the three
 * characters that separate standard base64 from base64url and exactly the three that get
 * mangled by a careless URL decode.
 */
class ContactQrTest {

    /** `OSHI/QRCodeDisplayView.swift:334`. */
    private val KEY = "kr/6aAArDrl91TOXf/bjv2u1SiRf+H8gIi8BBgPYpi0="

    /** A second real-shaped key, so "own key" tests have something to be different from. */
    private val OTHER = Base64.getEncoder().encodeToString(ByteArray(32) { (it * 7 + 3).toByte() })

    private fun addressOf(s: Any?): String = (s as ContactQr.Scan.Contact).address
    private fun reasonOf(s: Any?): ContactQr.Reason = (s as ContactQr.Scan.Rejected).reason

    // ────────────────────────────────────────────────── the payload itself

    /**
     * The fixture is what the doc comment claims it is. If this fails, every other
     * assertion in this file is measuring the wrong thing.
     */
    @Test
    fun `the shipped key literal is standard base64 of thirty-two bytes`() {
        assertEquals(44, KEY.length)
        assertEquals(32, Base64.getDecoder().decode(KEY).size)
        assertTrue("contains the standard-alphabet '/'", KEY.contains('/'))
        assertTrue("contains the standard-alphabet '+'", KEY.contains('+'))
        assertTrue("is '='-padded", KEY.endsWith("="))
        assertFalse("must NOT contain the base64url '-'", KEY.contains('-'))
        assertFalse("must NOT contain the base64url '_'", KEY.contains('_'))
    }

    /**
     * The QR payload is the bare key. `QRCodeDisplayView.swift:272` encodes
     * `Data(self.publicKey.utf8)`; `QRCodeScreen.kt:69` encodes `publicKey`.
     *
     * No prefix, no scheme, no URL, no JSON. This is the assertion that a future
     * "improvement" adding a version prefix has to argue with.
     */
    @Test
    fun `the qr payload is the raw key with nothing wrapped around it`() {
        val payload = ContactQr.payloadFor(KEY)
        assertEquals(KEY, payload)
        assertFalse(payload.startsWith("oshi:"))
        assertFalse(payload.startsWith("http"))
        assertFalse(payload.startsWith("{"))
    }

    @Test
    fun `the qr payload is standard base64 and never base64url`() {
        val payload = ContactQr.payloadFor(KEY)
        assertFalse("emitting '-' would break V2 TOFU byte equality", payload.contains('-'))
        assertFalse("emitting '_' would break V2 TOFU byte equality", payload.contains('_'))
        // A base64url spelling ARRIVES fine and is folded back before it is ever emitted.
        val urlSpelling = KEY.replace('+', '-').replace('/', '_').trimEnd('=')
        assertEquals(KEY, ContactQr.payloadFor(urlSpelling))
    }

    @Test(expected = IllegalArgumentException::class)
    fun `refusing to encode a qr for something that is not a key`() {
        ContactQr.payloadFor("not-a-key")
    }

    // ────────────────────────────────────────────────── parse: the three shipped forms

    @Test
    fun `a bare key scans`() {
        assertEquals(KEY, addressOf(ContactQr.parse(KEY, OTHER)))
    }

    /**
     * The legacy Android contact QR. `NewMessageScreen.kt:89` still strips this prefix
     * because codes printed by older builds are still in the world; iOS never did, which
     * is the bug that comment records.
     */
    @Test
    fun `the legacy oshi-colon android qr still scans`() {
        assertEquals(KEY, addressOf(ContactQr.parse("oshi:$KEY", OTHER)))
    }

    /**
     * The link iOS shares. `.urlQueryAllowed` does NOT escape `+`, `/` or `=`
     * (`QRCodeDisplayView.swift:41`), so the key rides raw — and a parser that runs
     * `URLDecoder.decode` over this turns the `+` into a SPACE and silently corrupts it.
     * That is Android `normalizeScannedContactPayload`'s shipped bug
     * (`NewMessageScreen.kt:83-86`); this asserts the desktop does not have it.
     */
    @Test
    fun `the ios link with a raw plus keeps the plus`() {
        val link = "https://oshi-messenger.org/add?key=$KEY"
        assertTrue("fixture must contain a raw '+'", link.contains('+'))
        assertEquals(KEY, addressOf(ContactQr.parse(link, OTHER)))
    }

    /**
     * The link Android shares: `URLEncoder.encode` (`QRCodeScreen.kt:186`) turns `+`,
     * `/` and `=` into `%2B`, `%2F` and `%3D`. Both forms are in the wild; Android's own
     * `DeepLinkParserTest` has a test for each.
     */
    @Test
    fun `the android link with percent escapes decodes`() {
        val encoded = KEY.replace("+", "%2B").replace("/", "%2F").replace("=", "%3D")
        assertEquals(KEY, addressOf(ContactQr.parse("https://oshi-messenger.org/add?key=$encoded", OTHER)))
    }

    @Test
    fun `the custom scheme and the short k alias both work`() {
        assertEquals(KEY, addressOf(ContactQr.parse("oshi://add?key=$KEY", OTHER)))
        assertEquals(KEY, addressOf(ContactQr.parse("https://oshi-messenger.org/add?k=$KEY", OTHER)))
        assertEquals(KEY, addressOf(ContactQr.parse("https://oshi-messenger.com/add?src=qr&key=$KEY&v=2", OTHER)))
    }

    // ────────────────────────────────────────────────── parse: hosts

    /** `OSHI.entitlements:13-17` + `SharedContentHandler.swift:64-65`. */
    @Test
    fun `every host the phones accept is accepted`() {
        for (host in listOf(
            "oshi-messenger.com", "www.oshi-messenger.com",
            "oshi-messenger.org", "www.oshi-messenger.org",
            "OSHI-Messenger.ORG",
        )) {
            assertEquals("host $host", KEY, addressOf(ContactQr.parse("https://$host/add?key=$KEY", OTHER)))
        }
    }

    /**
     * Foreign hosts are refused. iOS's SCAN path does not do this at all
     * (`MessagesListView.swift:474-480` takes the `key` out of any URL), so a printed
     * `https://evil.com/add?key=<attacker>` is accepted by an iPhone. Android's
     * `DeepLinkParser` refuses, and this takes Android's side.
     */
    @Test
    fun `foreign and lookalike hosts are refused`() {
        for (url in listOf(
            "https://evil.com/add?key=$KEY",
            "https://oshi-messenger.com.evil.com/add?key=$KEY",
            "https://notoshi-messenger.org/add?key=$KEY",
            "https://oshi-messenger.net/add?key=$KEY",
            "https://oshi-messenger.org@evil.com/add?key=$KEY",
        )) {
            assertEquals("must refuse $url", ContactQr.Reason.FOREIGN_HOST, reasonOf(ContactQr.parse(url, OTHER)))
        }
    }

    @Test
    fun `port and userinfo do not defeat the host check`() {
        assertEquals(KEY, addressOf(ContactQr.parse("https://oshi-messenger.org:443/add?key=$KEY", OTHER)))
        assertEquals(KEY, addressOf(ContactQr.parse("https://user@oshi-messenger.org/add?key=$KEY", OTHER)))
    }

    /** iOS handles `https` only — `SharedContentHandler.swift:62`. */
    @Test
    fun `plain http is not one of ours`() {
        val scan = ContactQr.parse("http://oshi-messenger.org/add?key=$KEY", OTHER)
        // Not FOREIGN_HOST: an `http` URL is not an OSHI link at all, so it falls through
        // to the bare-key branch and is refused for not being a key.
        assertEquals(ContactQr.Reason.NOT_AN_IDENTITY_KEY, reasonOf(scan))
    }

    // ────────────────────────────────────────────────── parse: pasted text

    /**
     * The whole share message, pasted. `NewMessageView.swift:720-729` wraps the key in
     * ⟦…⟧ so a data detector has a boundary to stop at; `MessagesListView.swift:490-496`
     * is the matching extraction.
     */
    @Test
    fun `the full ios share message parses`() {
        val shared = """
            Add me on OSHI!

            https://oshi-messenger.org/add?key=$KEY

            My public key:
            ⟦$KEY⟧

            Copy everything between the brackets.
        """.trimIndent()
        assertEquals(KEY, addressOf(ContactQr.parse(shared, OTHER)))
    }

    /**
     * The exact corruption `NewMessageView.swift:711` records: pasted into another app,
     * iOS's data detectors latched onto the trailing base64 and appended a unit
     * conversion — "…muFE3A=0.0741 acre" — and the contact silently failed to add.
     */
    @Test
    fun `a detector-appended tail is trimmed off an unwrapped paste`() {
        assertEquals(KEY, addressOf(ContactQr.parse("$KEY 0.0741 acre", OTHER)))
        assertEquals(KEY, addressOf(ContactQr.parse("$KEY,0.0741 acre", OTHER)))
    }

    @Test
    fun `our own share text round trips through our own parser`() {
        // Not circular: the ASSERTION is the shipped key, and the share text's shape is
        // pinned by the separate literal-checking test below.
        assertEquals(KEY, addressOf(ContactQr.parse(ContactQr.shareText(KEY), OTHER)))
    }

    @Test
    fun `the share text keeps the key between brackets and never last`() {
        val text = ContactQr.shareText(KEY)
        assertTrue(text.contains("⟦$KEY⟧"))
        assertFalse("the key must never be the final token", text.trimEnd().endsWith(KEY))
        assertTrue(text.contains("https://oshi-messenger.org/add?key="))
    }

    @Test
    fun `the shared deep link percent-encodes the base64 characters`() {
        val link = ContactQr.deepLinkFor(KEY)
        assertTrue(link.startsWith("https://oshi-messenger.org/add?key="))
        val query = link.substringAfter("key=")
        assertFalse("a raw '+' in a query is ambiguous with a space", query.contains('+'))
        assertFalse(query.contains('/'))
        assertFalse(query.contains('='))
        assertTrue(query.contains("%2B") || query.contains("%2F"))
        // …and it comes back out intact.
        assertEquals(KEY, addressOf(ContactQr.parse(link, OTHER)))
    }

    // ────────────────────────────────────────────────── validation

    /**
     * Both phones accept anything at least 20 characters long
     * (`NewMessageView.swift:124`, `NewMessageScreen.kt:153`). The desktop does not: the
     * failure otherwise surfaces much later, inside `require(keyBytes.size == 32)`, or as
     * a session that can never be established.
     */
    @Test
    fun `twenty characters of junk passes both phones and is refused here`() {
        val junk = "abcdefghijklmnopqrstuvwx"   // 24 chars, valid base64, 18 bytes
        assertTrue("fixture must clear the phones' >=20 gate", junk.length >= 20)
        assertEquals(ContactQr.Reason.NOT_AN_IDENTITY_KEY, reasonOf(ContactQr.parse(junk, OTHER)))
    }

    @Test
    fun `keys of the wrong byte length are refused`() {
        for (n in intArrayOf(0, 1, 16, 31, 33, 64)) {
            val wrong = Base64.getEncoder().encodeToString(ByteArray(n))
            assertNull("$n bytes must not canonicalise", ContactQr.canonicalAddress(wrong))
        }
        assertNull(ContactQr.canonicalAddress(Base64.getEncoder().encodeToString(ByteArray(32)) + "A"))
    }

    @Test
    fun `own key is refused`() {
        assertEquals(ContactQr.Reason.OWN_KEY, reasonOf(ContactQr.parse(KEY, KEY)))
        // …including when the two sides spell it differently, which is precisely how a
        // self-scan slips through an exact-string check.
        val urlSpelling = KEY.replace('+', '-').replace('/', '_').trimEnd('=')
        assertEquals(ContactQr.Reason.OWN_KEY, reasonOf(ContactQr.parse(urlSpelling, KEY)))
    }

    @Test
    fun `empty input is named as empty rather than as a bad key`() {
        for (raw in listOf(null, "", "   ", "\n\t ")) {
            assertEquals(ContactQr.Reason.EMPTY, reasonOf(ContactQr.parse(raw, OTHER)))
        }
    }

    @Test
    fun `malformed input never throws`() {
        for (raw in listOf(
            "://", "oshi", "oshi:", "oshi:add?key=x", "https://", "https://oshi-messenger.org",
            "not a url at all", "%%%", "https://oshi-messenger.org/add?key=%zz",
            "javascript:alert(1)", "file:///etc/passwd", "⟦⟧", "⟧$KEY⟦",
            "https://oshi-messenger.org/add?keys=$KEY", "https://oshi-messenger.org/add?key=",
        )) {
            ContactQr.parse(raw, OTHER)   // must return, not throw
        }
    }

    // ────────────────────────────────────────────────── canonicalisation

    /**
     * The fold, and the ONE thing it must never do: manufacture a valid-looking string
     * out of a body whose length mod 4 is 1, which cannot be base64 at all.
     */
    @Test
    fun `canonicalisation folds base64url and repads, and refuses the impossible length`() {
        assertEquals(KEY, ContactQr.canonicalAddress(KEY))
        assertEquals(KEY, ContactQr.canonicalAddress(KEY.trimEnd('=')))
        assertEquals(KEY, ContactQr.canonicalAddress("  $KEY  "))
        assertEquals(KEY, ContactQr.canonicalAddress(KEY.replace('+', '-').replace('/', '_')))
        assertNull(ContactQr.canonicalAddress("A".repeat(41)))   // 41 % 4 == 1
        assertTrue(ContactQr.isIdentityKey(KEY))
        assertFalse(ContactQr.isIdentityKey("oshi:$KEY"))
    }

    // ────────────────────────────────────────────────── the two halves meet

    /** The display half and the parse half agree, through a real encoded matrix. */
    @Test
    fun `what we encode is what a scanner would hand back`() {
        val payload = ContactQr.payloadFor(KEY)
        val qr = QrMatrix.encode(payload)
        assertEquals(4, qr.version)
        assertEquals(KEY, addressOf(ContactQr.parse(payload, OTHER)))
    }
}
