package com.oshi.desktop.pairing

import java.awt.Color
import java.awt.image.BufferedImage
import java.io.File
import javax.imageio.ImageIO
import kotlin.io.path.createTempDirectory
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class QrImageDecoderTest {
    @Test
    fun `a QR image generated by OSHI decodes to its exact contact payload`() {
        val payload = "oshi://add?key=AbCdEfGhIjKlMnOpQrStUvWxYz0123456789+/="
        val matrix = QrMatrix.encode(payload)
        val module = 8
        val quiet = 4
        val image = BufferedImage((matrix.size + quiet * 2) * module, (matrix.size + quiet * 2) * module, BufferedImage.TYPE_INT_RGB)
        val g = image.createGraphics()
        g.color = Color.WHITE
        g.fillRect(0, 0, image.width, image.height)
        g.color = Color.BLACK
        for (row in 0 until matrix.size) for (column in 0 until matrix.size) if (matrix.dark(row, column)) {
            g.fillRect((column + quiet) * module, (row + quiet) * module, module, module)
        }
        g.dispose()
        val file = temporaryPng(image)
        try {
            assertEquals(payload, QrImageDecoder.decode(file).getOrThrow())
        } finally {
            file.delete()
        }
    }

    @Test
    fun `an ordinary image is refused rather than interpreted as a contact`() {
        val image = BufferedImage(32, 32, BufferedImage.TYPE_INT_RGB)
        val file = temporaryPng(image)
        try {
            assertTrue(QrImageDecoder.decode(file).isFailure)
        } finally {
            file.delete()
        }
    }

    private fun temporaryPng(image: BufferedImage): File {
        val file = createTempDirectory("oshi-qr-image").resolve("code.png").toFile()
        ImageIO.write(image, "png", file)
        return file
    }
}
