package com.oshi.desktop.i18n

import org.json.JSONObject
import java.io.InputStream
import java.nio.charset.StandardCharsets

/**
 * One locale's strings, as the desktop client carries them.
 *
 * ## Why JSON files in the jar, and not `ResourceBundle`
 *
 * The obvious JVM answer to "34 locales" is `ResourceBundle` over `.properties`. It was
 * rejected for three reasons, each of which is a defect this project has already been
 * burned by in another form:
 *
 * 1. **`ResourceBundle.getBundle` falls back through the JVM's DEFAULT LOCALE** before it
 *    reaches the base bundle. So `getBundle("s", FRENCH)` on a machine whose default is
 *    German returns GERMAN strings for anything French is missing — and the same call on
 *    a CI runner set to `en_US` returns English. That is a fallback chain that changes
 *    with the machine, which makes every assertion about it environment-dependent. This
 *    project has a memory of exactly that shape: a localisation test that passed or
 *    failed on the simulator's `AppleLanguages` rather than on the code. [Strings] has an
 *    EXPLICIT chain instead, with no `Locale.getDefault()` anywhere in the lookup path.
 * 2. **`.properties` mangles values.** `Properties` strips leading whitespace from a
 *    value and treats `:` and `=` as separators. OSHI keys are dotted and safe, but its
 *    values include leading spaces and colons, and a format that quietly rewrites the
 *    asset is the wrong container for an asset whose whole point is that it was already
 *    translated and paid for.
 * 3. **`ResourceBundle` has no way to say "missing".** It throws `MissingResourceException`
 *    or returns the key, depending on how it is wrapped, and neither is observable to an
 *    audit. Here a miss goes through [Strings.onMissingKey], so a test can COUNT misses.
 *
 * JSON also costs nothing: `org.json` is already a runtime dependency of this project
 * (pinned to what OSHI-Android uses), so this adds no dependency at all — working rule 4.
 *
 * ## Why the files are checked in, not read from the iOS tree
 *
 * `src/main/resources/i18n/` is generated by [com.oshi.desktop.i18n.tools.CatalogExtractor]
 * and COMMITTED. The desktop build must work on a Windows and a Linux runner that have
 * never seen `OSHI/`, and the packaged `.msi` must contain the 34 locales — an installed
 * app has no sibling iOS checkout to read. Generating into `build/` would make the
 * catalogs present exactly on the machine that has the iOS tree and absent on the two
 * platforms this whole port exists for, and the app would ship English-only without one
 * line of the build going red.
 *
 * The cost of checking generated files in is drift, so drift is measured:
 * `CatalogFreshnessTest` re-runs the extractor against the iOS tree WHEN THAT TREE IS
 * PRESENT and fails on any difference.
 */
class Catalog(
    /** BCP-47 tag as the catalog is filed, e.g. `fr`, `pt-BR`, `zh-Hans`. */
    val tag: String,
    private val entries: Map<String, String>,
) {
    val size: Int get() = entries.size
    val keys: Set<String> get() = entries.keys

    /**
     * The raw string for [key], or null.
     *
     * A **blank** value is a miss, not a hit. A translator who leaves `"x" = "";` produces
     * a catalog that is 100% "present" and an app with a hole in it; treating blank as
     * absent means such a key falls through to English and is counted as missing by the
     * coverage report, which is what it is.
     */
    operator fun get(key: String): String? = entries[key]?.takeIf { it.isNotBlank() }

    /** Every key whose value is present but blank — a translation that is not one. */
    fun blankKeys(): Set<String> = entries.filterValues { it.isBlank() }.keys

    fun asMap(): Map<String, String> = entries

    companion object {
        fun read(tag: String, stream: InputStream): Catalog {
            val text = stream.readBytes().toString(StandardCharsets.UTF_8)
            val obj = JSONObject(text)
            val map = HashMap<String, String>(obj.length() * 2)
            for (k in obj.keys()) map[k] = obj.getString(k)
            return Catalog(tag, map)
        }

        /**
         * Serialize deterministically: keys sorted, one per line, UTF-8, no escaping of
         * non-ASCII. Deterministic because these files are checked in, and a diff that
         * churns on map iteration order makes drift invisible in review.
         */
        fun write(entries: Map<String, String>): String {
            val sb = StringBuilder("{\n")
            val sorted = entries.keys.sorted()
            sorted.forEachIndexed { i, k ->
                sb.append("  ").append(JSONObject.quote(k)).append(": ")
                    .append(JSONObject.quote(entries.getValue(k)))
                if (i < sorted.size - 1) sb.append(',')
                sb.append('\n')
            }
            return sb.append("}\n").toString()
        }
    }
}
